apiVersion: v1
kind: Service
metadata:
    name: mysql-service
spec:
    type: ClusterIP
    ports:
    - name: sql
      port: 3306
      targetPort: 3306
      protocol: TCP
    selector:
        app: mysql-app

---

apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
   name: mysql-storage
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
      - name: mysql
        image: mysql-image
        ports:
        - containerPort: 3306
          name: sql
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /livenessprobe.sh
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-storage		  
