apiVersion: v1
kind: Service
metadata:
    name: grafana-service
    annotations:
        metallb.universe.tf/allow-shared-ip: unifi-addr
spec:
    type: LoadBalancer
    loadBalancerIP: 192.168.99.232
    ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
    selector:
        app: grafana-app
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana-app
    spec:
      containers:
      - name: grafana
        image: grafana-image
        ports:
        - containerPort: 3000
          name: http
        imagePullPolicy: Never
