apiVersion: v1
kind: Service
metadata:
    name: nginx-service
    annotations:
        metallb.universe.tf/allow-shared-ip: unifi-addr
spec:
    type: LoadBalancer
    loadBalancerIP: 192.168.99.232
    ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name:	ssh
      port: 22
      targetPort: 22
      protocol: TCP 
    selector:
        app: nginx-app
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx-image
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh
        imagePullPolicy: Never
        env: 
        - name: SSH_USER
          value: admin
        - name: SSH_PASSWORD
          value: admin
