apiVersion: v1
kind: Service
metadata:
    name: wordpress-service
    annotations:
        metallb.universe.tf/allow-shared-ip: unifi-addr
spec:
    type: LoadBalancer
    loadBalancerIP: 192.168.99.232
    ports:
    - name: http
      port: 5050
      targetPort: 5050
      protocol: TCP
    selector:
        app: wordpress-app
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
      - name: wordpress
        image: wordpress-image
        ports:
        - containerPort: 5050
          name: http
        imagePullPolicy: Never
