apiVersion: v1
kind: Service
metadata:
    name: ftps-service
    annotations:
      metallb.universe.tf/allow-shared-ip: unifi-addr
spec:
    type: LoadBalancer
    loadBalancerIP: 192.168.99.232
    ports:
    - name: http
      port: 21
      targetPort: 21
      protocol: TCP
    - name: ftps1
      port: 21000
      targetPort: 21000
      protocol: TCP
    - name: ftps2
      port: 21001
      targetPort: 21001
      protocol: TCP
    - name: ftps3
      port: 21002
      targetPort: 21002
      protocol: TCP
    - name: ftps4
      port: 21003
      targetPort: 21003
      protocol: TCP
    - name: ftps5
      port: 21004
      targetPort: 21004
      protocol: TCP
    selector:
        app: ftps-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps-app
    spec:
      containers:
      - name: ftps
        image: ftps-image
        ports:
        - containerPort: 21
          name: http
        - containerPort: 21000
          name: ftps1
        - containerPort: 21001
          name: ftps2
        - containerPort: 21002
          name: ftps3
        - containerPort: 21003
          name: ftps4
        - containerPort: 21004
          name: ftps5
        imagePullPolicy: Never
